services:
  fastapi:
    build:
      context: ./app
    ports:
     - "8000:8000"
    models:
      - llm
  
  ui:
    build:
      context: ./ui
    ports:
     - "8501:8501"
    depends_on:
     - fastapi
  
    
models:
  llm:
    model: ai/smollm2
